### PR TITLE
chore: add dev tooling

### LINKED ISSUE #13: Integrate codebase with development tools
Like pylint, isort and others.

### PR DESCRIPTION
**Pull request by scop**
Closes #13 

Draft: what I suggest doing still before merging, pending @guludo's opinion, can take care of these if it sounds good

- [x] Add [black](https://github.com/psf/black)
  - [x] Reformat with black, default settings
- [x] Add [pre-commit](https://pre-commit.com) config for all tools here
- [x] Run all this stuff in CI, with pre-commit
- [x] Pin these tools with exact versions
  - [ ] Set up [Renovate](https://github.com/renovatebot/renovate) to update them (Renovate instead of dependabot, because the latter doesn't support pre-commit)

### CODE REVIEW

**Comment by guludo** [comment]
Hi. I think all those suggests sound great!

The current code is small, but I think also having coverage would be nice. Not a blocker though.

**Review by guludo — APPROVED** [review]
I didn't take that much time to learn how to configure renovate, but overall this changeset looks good.

Thanks a lot for this, @scop!

**Comment by scop** [comment]
Ok, merged. The `==`  tool dependencies are a bit of a chore to maintain manually without Renovate though, and the configuration is already in place with this MR -- I don't think there's anything more to do than to click "install" from the above marketplace link and granting it access to this project from the settings (if that's even needed, I'm not sure). So when you find a couple of minutes sometime, going through it would be nice :+1:

**Comment by scop** [comment]
Ah, perhaps Renovate was enabled already after all -- at least there was an issue with the schedule syntax, fix in #23

**Comment by guludo** [comment]
> Ah, perhaps Renovate was enabled already after all

Yep. I did that before approving the PR :-)

**Pull request merged**
